import axios from "axios";
import { GetStaticProps } from "next";
import Head from "next/head";
import { Card } from "../components/Card";

export default function Home({ beers }: any) {
  return (
    <div className="bg-orange-50">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-4 gap-2 p-8">
        {beers.map((beer: any) => (
          <Card key={beer.id} description={beer.description} thumb={beer.image_url} title={beer.name} />
        ))}
      </div>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const url = "https://api.punkapi.com/v2/beers";

  const res = await axios.get(url);
  const { data: beers } = res;

  return {
    props: {
      beers,
    },
    revalidate: 60 * 60 * 3, // 3 hours
  };
};
